module.exports = {

  USER_ROLE: {
    ADMIN: 'ADMIN',
    SYSTEM_ADMIN: 'SYSTEM_ADMIN',
  },
    DEVICE_STATUS: {
    ACTIVE: 'ACTIVE',
    INACTIVE: 'INACTIVE',
    OFFLINE: 'OFFLINE',
  },
  ALERT_STATUS: {
    OPEN: 'OPEN',
    RESOLVED: 'RESOLVED',
    ACKNOWLEDGED: 'ACKNOWLEDGED',
  },
  TRANSACTION_STATUS: {
    ACTIVE: 'ACTIVE',
    AWAITING_USER_CONFIRMATION: 'AWAITING_USER_CONFIRMATION',
    COMPLETED: 'COMPLETED',
    DISPUTED: 'DISPUTED',
    CANCELLED: 'CANCELLED',
    FAILED: 'FAILED',
  },
  ACCESS_REASON: {
    OK: 'OK',
    DEVICE_OFFLINE: 'DEVICE_OFFLINE',
    DEVICE_INACTIVE: 'DEVICE_INACTIVE',
    SESSION_LIMIT_REACHED: 'SESSION_LIMIT_REACHED',
    DOOR_ALREADY_OPEN: 'DOOR_ALREADY_OPEN',
    ACTIVE_SESSION_EXISTS: 'ACTIVE_SESSION_EXISTS',
  },
  
  ACTION_TYPE: {
    ADD: 'ADD',
    REMOVE: 'REMOVE',
  },
  
  DISPUTE_REASON: {
    WRONG_ITEM: 'WRONG_ITEM',
    MISSING_ITEM: 'MISSING_ITEM',
    OTHER: 'OTHER',
  },
  

  SESSION_INIT_TOKEN_EXPIRY_SECONDS: 60,
  DEVICE_OFFLINE_THRESHOLD_MINUTES: 5,
};

