module.exports = {

  USER_ROLE: {
    ADMIN: 'ADMIN',
    SYSTEM_ADMIN: 'SYSTEM_ADMIN',
  },
    DEVICE_STATUS: {
    ACTIVE: 'ACTIVE',
    INACTIVE: 'INACTIVE',
    OFFLINE: 'OFFLINE',
  },

  SESSION_INIT_TOKEN_EXPIRY_SECONDS: 60,
};

