module.exports = {

  USER_ROLE: {
    ADMIN: 'ADMIN',
    SYSTEM_ADMIN: 'SYSTEM_ADMIN',
  },
    DEVICE_STATUS: {
    ACTIVE: 'ACTIVE',
    INACTIVE: 'INACTIVE',
    OFFLINE: 'OFFLINE',
  },
  ALERT_STATUS: {
    OPEN: 'OPEN',
    RESOLVED: 'RESOLVED',
    ACKNOWLEDGED: 'ACKNOWLEDGED',
  },
  

  SESSION_INIT_TOKEN_EXPIRY_SECONDS: 60,
  DEVICE_OFFLINE_THRESHOLD_MINUTES: 5,
};

